name: wheels

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # Only trigger on version tags like v1.0.0
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build Python wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Build wheel and sdist
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: dist/*

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # Only publish to PyPI on version tags or releases
    if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
